services:
  mongodb:
    image: mongo:7
    container_name: vamo-heatos-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: vamo-heatos

volumes:
  mongo-data:
